"""create scholarship tables

Revision ID: b5bccd2c51c4
Revises: 
Create Date: 2026-06-08 12:31:15.622309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5bccd2c51c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('application_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scholarship_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('father_name', sa.String(length=255), nullable=False),
    sa.Column('mother_name', sa.String(length=255), nullable=False),
    sa.Column('institute_name', sa.String(length=255), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('percent_12th', sa.Float(), nullable=False),
    sa.Column('category_certificate', sa.String(), nullable=True),
    sa.Column('recent_sem_marksheet', sa.String(), nullable=False),
    sa.Column('marksheet_12th', sa.String(), nullable=False),
    sa.Column('id_card', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('roll', sa.String(), nullable=False),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('verified_by_authority', sa.Boolean(), nullable=True),
    sa.Column('verified_by_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('approved_applications',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('scholarship_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('institute', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('renewal_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('application_id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('scholarship',
    sa.Column('scholarship_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('total_applicants', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('scholarship_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('scholarship')
    op.drop_table('approved_applications')
    op.drop_table('application')
    # ### end Alembic commands ###
